### ISSUE TITLE
Modificaciones datos personales `

### ISSUE THREAD

**Issue by fedexdiaz** [siisp/websystem#16]
- Agregar foto de prfil
- Agregar fecha de nacimiento

**Comment by CasaboneLucas** [comment]
-Agregar foto de perfil:
        Según el género del investigador, se tendrá una foto de  perfil pro defecto acorde al genero del mismo.

**Comment by fedexdiaz** [comment]
@CasaboneLucas el código esta muy bien. No hay nada para modificar
