### ISSUE TITLE
Modificaciones de Datos de Formacion

### ISSUE THREAD

**Issue by fedexdiaz** [siisp/websystem#18]

**Comment by fedexdiaz** [comment]
Sacar todos los campos actuales
- Agregar el campo Tipo de Formacion, seleccionable, a agregar (Grado, Posgrado). Es decir que un investigadortiene varias formacciones. Cada Formacion tiene los siguientes campos:
  - Campo  Disciplina (actual titulo de grado)
  - Maximo titulo académico 
  - Estado (Terminado, En curso)
 - Si esta en curso que aparezcan los campos de beca.
   - Tipo de beca (seleccionable)
  - Nombre de la beca (seleccionable)
 - Si elige tipo de beca otro, que aparezca texto libre

**Comment by CasaboneLucas** [comment]
-En donde dice "Nombre de la beca (seleccionable)", ¿ esto aparecería solo si esta el estado en curso?

**Comment by fedexdiaz** [comment]
Estas serian las estrategias:

Estrategia de persistencia

Researchers
 -AB1 
  formations 
    -AB123
    	TipoFormacion: Grado
	CampoDisciplina: -AB2334
	MaximoTituloAcademico: -ASDADA
	Estado: Terminado
     -AB124
    	TipoFormacion: Grado
	CampoDisciplina: -AB2334
	MaximoTituloAcademico: -ASDADA
	Estado: EnCurso
	TipoBeca: -ABR3



Estrategia para mostrar por referencia

<ng-repeat="r from researchers">
r.name
r
<ng-repeat="f from r.formations">

f.TipoFormacion
parametrics.disciplinas[f.CampoDisciplina].name

<>

**Comment by CasaboneLucas** [comment]
Agrege las instancias de Tipo de becha y nombre de becha y el campo de texto libre.

**Comment by fedexdiaz** [comment]
@CasaboneLucas  CR
1- El estado de una formacion (En Curso o Terminada) deberia guardarse como un boleano: completed  (true cuando esta Terminada y false cuando esta en curso). Y se debe visualizar como texto. Guardar este tipo de dato de esta forma es más eficiente para busquedas y filtrados  en la base de datos.

**Comment by CasaboneLucas** [comment]
@fedexdiaz 
Ya implementado.
