### ISSUE TITLE
Modificaciones de Datos Académicos

### ISSUE THREAD

**Issue by fedexdiaz** [siisp/websystem#20]
- Sacar los campos: CAlidad de Integrante, Beca/Institucion, Lugar de trabajo...
-  Los otros 3 campos corresponden a radicaciones. Los investigadores pueden tener más de una radicación en UNDAV
  - Agregar un campo para definir si tiene asignación no docente. (Check box si o no) y agregar un campo donde (Campo seleccionanable Secretaria/ Departamento)

**Comment by CasaboneLucas** [comment]
El campo de la asignación no docente, ¿Estaría fuera de la radicación?. Es decir, ¿es independiente de eso?
No comprendí lo de agregar un Campo seleccionanable Secretaria/ Departamento siendo que ya hay uno en la radicación.

**Comment by fedexdiaz** [comment]
@CasaboneLucas  

Falta lo de asignación no docente pero me parece mejor dejar así como esta y crear con ellos la story para "Asignación no docente" así la entendemosbien. Porque sino es un lio.
