### ISSUE TITLE
Alta de parametricas

### ISSUE THREAD

**Issue by fedexdiaz** [siisp/websystem#22]

**Comment by fedexdiaz** [comment]
Controller

Setup()
$scope.parametricsItems = [{nombre: "Grado academico", childNodeId: "academicDegree"},{nombre: "Carrera", childNodeId: "carrer"}]
$scope.paremetricEditing = {}

Save
paremitricService.Save(scope.childNodeIdOfselectParametric, $scope.paremetricEditing)
 


Vista

select parametricsItems -> childNodeId -> $scope.childNodeIdOfselectParametric
input name -> $scope.paremetricEditing.name


Service
saveParametric(parametricType, parametric)
{
dataService.Save('parametrics\'+ parametricType, parametric)
}

**Comment by fedexdiaz** [comment]
@CasaboneLucas 
Code Review:
1- Separar la lógica de alta. Cambios en la Vista: Crear new.html con el formulario que tenes en index.html.  Cambios en el controlador: sacar la logica de alta de parametrics.index y ponerla bien en parametrics.new.

2- Separar la lógica de edición en linea. Cambios en la vista: Crear editInLine.html y mover el elemento html table que esta en index.html.   Crear el controlador parametrics.editInLine y mover toda la lógica que hace la edicion de esa vista

Con estos 2 cambios parametrics.index (el controlador  y su vista)  solo tendría la responsabilidad de cargar todas las parametricsTypes,  establecer el valor de  parametricTypeSelected. Tener en cuenta que el scope de parametrics.index va a ser el scope padre de parametrics.new y parametrics.editInLine así que estos dos ultimos controladores van a poder utilizar las variables de ese scope.

3 - Cuando hay un alta de una parametrica validar que no exista otra con el mismo nombre. Para esto puede que se necesite mover de nuevo al scope padre (parametric.index) la carga de las parametricas.

**Comment by CasaboneLucas** [comment]
@fedexdiaz 
Ya se encuentra todo implementado.

**Comment by fedexdiaz** [comment]
@CasaboneLucas  Muy bueno!
Quedan algunos detalles: CR #2
1- En parametrics.new se puede sacar toda la logica que carga en $scope.parametrics porque ya esta en parametrics.index y el scope de parametrics.new es hijo the scope de parametrics.index
2- El metodo parametrics.new.save debe llama a parametricService.save($scope.parametricEditing, onParametricSaved);  Ese metodo no existe. Debería llamar a parametricService.saveParametric($scope. parametricTypeSelected,$scope.parametricEditing, onParametricSaved). Como es el scope del padre no habria problemas
3-Cuando hay uno duplicado, esta mostrando en texto rojo el error? estaria bueno ponerlo con el mismo estilo que tenemosen el formulario de investigadores (cuando algun campo es incorrecto o requerido). Actualmente simplemente no lo agrega y aparece la leyenda "guardado"

**Comment by CasaboneLucas** [comment]
@fedexdiaz 

Ya esta todo implementado. Voy a proceder a hacer el push asi podes hacer el deploy en staging.
