### ISSUE TITLE
Mostrar el Listado de Investigadores

### ISSUE THREAD

**Issue by fedexdiaz** [siisp/websystem#3]

**Comment by CasaboneLucas** [comment]
El listado ya está funcionando, falta agregarle diseño.

**Comment by fedexdiaz** [comment]
Code Review
list.html
#1 Si no hay investigadores pondría una leyenda que indique que no hay investigadores
#2 Faltan los botones Editar (una columna más en la tabla) y un botón Agregar Investigador. Podes ver cómo navegar en mechanics/index.html del proyecto mechanics (ver cómo se navega utilizando los atributos ui-sref)
#3 En la tabla sacaría el campo género y el campo “order” (de donde salió eso?).  
#4 En la tabla pondría primero el apellido, después el nombre, después el dni y finalmente el mail. Entonces la tabla se ordena por apellido y después por nombre
#5 Para ordenar los investigadores utilizaría el concepto de filters en angular. Esto hace que no exista código en el contralador (lo sacarías) y que vos puedas poner en la vista el orden utilizando el patrón “pipes” (|) que da una notación más simple y clara para saber cómo se ordena:
<tr ng-repeat="researcher in researchers | toArray | orderBy:'surname'}">
 El filter toArray habria que crearlo. Agregando un archivo coreFilters.js en el módulo core. El código es cómo el que tenes en el controller, pero creando un filter:

angular.module('Core').filter('toArray', function() {
    return function(obj) {
        var result = [];
        angular.forEach(obj, function(val) {
            result.push(val);
        });
        return result;
    };
});

El filter orderBy es nativo de angular, así que no hay implementar nada con respecto a eso.

#5 Tabular e identar y poner nuevas líneas uniformemente en el controller researchers.list
#Los diseños lo podemos dejar para la story número 6
