### ISSUE TITLE
Fix en el formulario de alta de parametrica

### ISSUE THREAD

**Issue by fedexdiaz** [siisp/websystem#30]

**Comment by fedexdiaz** [comment]
1 - Limpiar el formulario siempre que se agrega uno nuevo,para agregar otro
2 - Al cambiar eltipo de parametrica, limpiar el formulario

**Comment by CasaboneLucas** [comment]
@fedexdiaz 

Al agregar una nueva paramétrica se inicializa en null el id de parametricEditing. Esto soluciona los dos puntos.
