### ISSUE TITLE
Carrera y título academico son la misma paramétrica

### ISSUE THREAD

**Issue by fedexdiaz** [siisp/websystem#31]

**Comment by fedexdiaz** [comment]
- Quitar la parametrica Titulo Academico
- En el formulario de investigadores hacer los cambios para que use la parametrica Carrera

**Comment by CasaboneLucas** [comment]
@fedexdiaz 

Hay un problema. Porque la parametrica titulo académico es ahora grado de titulación (doctor, magister, etc). ¿Entonces sería disciplina? ¿ O disciplina es gran área de conocimiento?
