### ISSUE TITLE
Carrera Conicet y Categoria Conicet son lo  mismo

### ISSUE THREAD

**Issue by fedexdiaz** [siisp/websystem#32]

**Comment by CasaboneLucas** [comment]
@fedexdiaz 

Según lo que habíamos hablamos Carrera conicet seria un booleano de si/no.

Por otro lado, categoría conicet sería un valor que nos tienen que especificar.

¿Estas de acuerdo en que lo haga así?

**Comment by CasaboneLucas** [comment]
@fedexdiaz 

Ahora que lo pienso, si quitamos la solapa investigación, esta tarjeta no tiene uso.
