### ISSUE TITLE
Agregar la parametrica Grado de la titulacion

### ISSUE THREAD

**Issue by fedexdiaz** [siisp/websystem#34]

**Comment by fedexdiaz** [comment]
Esto es para decir si es Magister o Doctor o etc

**Comment by CasaboneLucas** [comment]
@fedexdiaz 

Una duda:

- ¿ Esto es algo que va a estar en el código o algo que se puede agregar (es decir, si esta en la base de datos) ?

**Comment by fedexdiaz** [comment]
Agregarlo en la base de datos. @CasaboneLucas
