### ISSUE TITLE
Definir tipos de parametricas

### ISSUE THREAD

**Issue by fedexdiaz** [siisp/websystem#35]

**Comment by fedexdiaz** [comment]
Definir tipos de parametricas. Simple, Compuesta. Cuando se guarda una parametrica siempre se debe establecer el tipo. El tipo de parametrica podria ser un atributo en el objeto parametricType.

Hacer que las parametricas: "Secretaria/Departamento" y "Carrera" sean del tipo compuesta

**Comment by CasaboneLucas** [comment]
@fedexdiaz 

Implementado.
