### ISSUE TITLE
Importar los datos de Carrera Conicet

### ISSUE THREAD

**Issue by fedexdiaz** [siisp/websystem#45]
Consultar esta información completa a Victoria. Si esta parametrica pasa a ser una parametrica compuesta, crear las stories necesarias para incorporarla (solamente crear la stories)

**Comment by CasaboneLucas** [comment]
@fedexdiaz 

Carrera conicet estaba en la solapa de "investigación", por lo cual esta story no se podra realizar ya que "investigación" fue quitada.
