### ISSUE TITLE
Poner las parametricas compuestas en el formulario de Investigadores para formación

### ISSUE THREAD

**Issue by fedexdiaz** [siisp/websystem#53]
El orden seria: Tipo de Formacion, Grado de titulacion \n Gran Area de Conocimiento, Carrera (distinta a carreras UNDAV, childs de Gran Area de)\n Estado Conocimiento),

**Comment by fedexdiaz** [comment]
@CasaboneLucas 
CR # 1
1 - Cuando se cambia un elemento del combo Gran Area de conocimiento, la carrera seleccionada deberia ponerse en null así no hay inconsistencias en la base de datos (el formulario de deja guardar una carrera que no pertenece a gran area de conocimiento).
2 - El listado de formaciones (y el formulario) debería tener el mismo comportamiento  que el de la solapa "i+d undav". Es decir que se deberían mostrar todos los campos en una tabla y al hacerclick en editarse deberia cargar en el formulario de arriba la edicion (y aparecer el boton cancelar)

**Comment by CasaboneLucas** [comment]
@fedexdiaz 

Listo

**Comment by fedexdiaz** [comment]
@CasaboneLucas 
CR #2
- El editar no funciona
- Rename: studiesState -> formationCompleted
