### ISSUE TITLE
Modificar el listado de Investigadores

### ISSUE THREAD

**Issue by fedexdiaz** [siisp/websystem#61]
Necesitamos 3 columnas
En la primer columna: Un resumen de los datos personales con la foto .
En la segunda columna: Un resumen de la formación.
En la tercer columna: Un resumen de los datos UNDAV

**Comment by CasaboneLucas** [comment]
@fedexdiaz 

Ya esta hecho, y quería proponer algo como un tooltip o similar, que cuando lo acciones te salga el detalle de , por ejemplo, la formación.
