### ISSUE TITLE
Luego de editar un investigador al ir a al listado de investigadores no se cargan

### ISSUE THREAD

**Issue by fedexdiaz** [siisp/websystem#67]

**Comment by CasaboneLucas** [comment]
@fedexdiaz 

Se resuelve el bug:

Al entrar por primera vez se cargaban los investigadores pero al volver de otra pagina nunca se refrescaba la lista filteredResearchers. Por lo cual la lista en un primer momento aparecía nula.

Esto se resuelve, ejecitanto el search() en el setup de modo que este inicializada siempre por primera vez filteredResearchers.

Por otro lado, la paginación no marcaba correctamente las páginas. Eso se debe al orden las definicones en el setup. Lo que generaba que llegue siempre vacia filteredResearchers a la función search().
